gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#986 -to=aCPLX128
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#977 -to=aCPLX64
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#957 -to=aFLOAT32
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#967 -to=aFLOAT64
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#930 -to=aINTER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#801 -to=aMEM
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#814 -to=aMEM0
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#852 -to=aMEM128
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#828 -to=aMEM16
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#836 -to=aMEM32
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#844 -to=aMEM64
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#821 -to=aMEM8
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#938 -to=aNILINTER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#861 -to=aNOEQ
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#868 -to=aNOEQ0
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#911 -to=aNOEQ128
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#884 -to=aNOEQ16
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#893 -to=aNOEQ32
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#902 -to=aNOEQ64
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#876 -to=aNOEQ8
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#949 -to=aSLICE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#921 -to=aSTRING
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#996 -to=aUNK
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gsubr.go:#13751 -to=anyregalloc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#14823 -to=arch
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/align.go:#14386 -to=argsize
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/obj.go:#285 -to=arhdrSize
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8604 -to=array_array
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8744 -to=array_cap
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8676 -to=array_nel
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/util.go:#935 -to=atExit
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#618 -to=bADWIDTH
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#2352 -to=bITS
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reflect.go:#1642 -to=bUCKETSIZE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#482 -to=bUFSIZ
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/plive.go:#1167 -to=basicBlock
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith2.go:#5097 -to=bconv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#2310 -to=bits
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#34056 -to=string
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/obj.go:#2914 -to=bputname
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#35829 -to=brcom
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/bv.go:#301 -to=bvec
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/cgen.go:#37665 -to=bvgen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#17966 -to=cLOAD
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#17993 -to=cREF
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6243 -to=cTCPLX
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6236 -to=cTFLT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6228 -to=cTRUNE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6251 -to=cTSTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6206 -to=cTxxx
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6405 -to=cboth
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gen.go:#9458 -to=cgen_As2dottype
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gen.go:#17312 -to=cgen_as
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gen.go:#17371 -to=cgen_as_wb
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gen.go:#6651 -to=cgen_eface
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gen.go:#5855 -to=clearslim
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/cplx.go:#5859 -to=complexgen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/cplx.go:#4350 -to=complexop
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6373 -to=crecv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6389 -to=csend
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6362 -to=cxxx
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/obj.go:#6600 -to=datastring
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/lex.go:#523 -to=debug_append
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reflect.go:#36116 -to=debug_gcprog
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/lex.go:#541 -to=debug_panic
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/lex.go:#559 -to=debug_slice
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#9605 -to=debug_typeassert
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/lex.go:#577 -to=debug_wb
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#17942 -to=deferproc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#17963 -to=deferreturn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#12597 -to=disable_checknil
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7777 -to=dlist
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/lex.go:#1898 -to=eOF
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7187 -to=eaddr
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7084 -to=easgn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6937 -to=ecall
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7286 -to=ecomplit
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#8661 -to=econv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6990 -to=efnstruct
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7132 -to=eindir
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7049 -to=eiota
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7240 -to=eproc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#310 -to=error
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6867 -to=erv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#11398 -to=escBits
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#11461 -to=escContentEscapes
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#6298 -to=escFuncPlanned
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#6314 -to=escFuncStarted
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#6330 -to=escFuncTagged
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#6271 -to=escFuncUnknown
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#11297 -to=escHeap
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#11421 -to=escMask
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#11343 -to=escNever
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#10933 -to=escNone
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#10996 -to=escReturn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#11554 -to=escReturnBits
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#11051 -to=escScope
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#13031 -to=escState
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#10914 -to=escUnknown
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6815 -to=etop
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6917 -to=etype
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#1419 -to=fDbg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#1406 -to=fErr
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#1425 -to=fExp
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#1431 -to=fTypeId
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith3.go:#3835 -to=fconv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#13002 -to=id
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#13050 -to=rpo
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#13090 -to=loop
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#13126 -to=refset
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#13166 -to=data
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#1532 -to=flusherrors
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4173 -to=func
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4188 -to=shortname
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4206 -to=enter
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4228 -to=exit
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4250 -to=cvars
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4345 -to=inldcl
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4402 -to=closgen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4418 -to=outerfunc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4436 -to=fieldtrack
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4456 -to=outer
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4500 -to=ntype
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4531 -to=top
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4584 -to=closure
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4627 -to=fCurfn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4645 -to=nname
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4664 -to=inl
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4723 -to=inlCost
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4738 -to=depth
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4754 -to=endlineno
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4772 -to=norace
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4841 -to=nosplit
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4907 -to=nowritebarrier
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4976 -to=dupok
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5025 -to=wrapper
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5067 -to=needctxt
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5146 -to=systemstack
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#12014 -to=funcdepth
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reflect.go:#36046 -to=gCProg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gen.go:#4240 -to=genlist
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#35357 -to=getoutarg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#13241 -to=num
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#13386 -to=rpo
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/plive.go:#42010 -to=h0
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/cgen.go:#56294 -to=hasLinkRegister
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#11798 -to=hasdefer
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#36652 -to=hconv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/plive.go:#42027 -to=hp
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7813 -to=idir
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/sinit.go:#272 -to=initDone
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5290 -to=initEntry
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5310 -to=xoffset
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5347 -to=expr
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/sinit.go:#252 -to=initNotStarted
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/sinit.go:#292 -to=initPending
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5411 -to=initPlan
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5430 -to=lit
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5442 -to=zero
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5454 -to=expr
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5466 -to=e
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7537 -to=io
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gsubr.go:#5885 -to=isfat
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#15136 -to=isfixedarray
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#15471 -to=isinter
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#10632 -to=isptr
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#15227 -to=isslice
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#15058 -to=istype
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5726 -to=iter
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5741 -to=done
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5752 -to=tfunc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5765 -to=t
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#4306 -to=jconv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#17780 -to=lOAD
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#18045 -to=lOOP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5011 -to=label
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5027 -to=used
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5039 -to=sym
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5050 -to=def
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5062 -to=use
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5078 -to=link
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5115 -to=gotopc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5166 -to=labelpc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5205 -to=breakpc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5244 -to=continpc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#8094 -to=level
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/plive.go:#2593 -to=liveness
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#5414 -to=lookupBytes
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#5316 -to=lookupf
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/lex.go:#20575 -to=loophack
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#553 -to=mAXALIGN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reflect.go:#1658 -to=mAXKEYSIZE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reflect.go:#1676 -to=mAXVALSIZE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/sinit.go:#11260 -to=mODECONST
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/sinit.go:#11245 -to=mODEDYNAM
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7916 -to=magic
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7932 -to=w
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7967 -to=s
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8003 -to=bad
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8102 -to=sd
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8139 -to=sm
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8224 -to=ud
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8262 -to=um
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#8296 -to=ua
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#6998 -to=maxFlowProg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#4794 -to=maxRgn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#649 -to=maxStackVarSize
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#11124 -to=maxintval
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#7054 -to=minLevel
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#11095 -to=minintval
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith2.go:#4139 -to=mpcmpfixfix
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1538 -to=mpcplx
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1555 -to=real
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1567 -to=imag
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1194 -to=mpdebug
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1459 -to=mpflt
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1475 -to=val
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith3.go:#3789 -to=string
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith2.go:#4328 -to=mpgetfix
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1259 -to=mpint
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1275 -to=val
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1289 -to=ovf
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1349 -to=rune
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith2.go:#5051 -to=string
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith2.go:#4481 -to=mpmovecfix
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith3.go:#2016 -to=mpmovecflt
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith3.go:#370 -to=mpmovefixflt
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1126 -to=mpprec
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/mparith2.go:#3294 -to=mpshiftfix
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#529 -to=nHASH
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#457 -to=nHUNK
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#506 -to=nSYMB
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6188 -to=nTYPE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#2362 -to=nVAR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#2874 -to=name
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#2889 -to=pack
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#2941 -to=pkg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3036 -to=inlvar
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3088 -to=defn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3132 -to=curfn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3181 -to=param
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3199 -to=decldepth
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3277 -to=vargen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3386 -to=iota
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3433 -to=funcdepth
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3450 -to=method
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3484 -to=readonly
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3500 -to=captured
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3557 -to=byval
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#17923 -to=newproc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1958 -to=nilVal
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#7342 -to=nod
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#564 -to=ninit
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#581 -to=nbody
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#598 -to=list
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#615 -to=rlist
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#808 -to=e
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#875 -to=lineno
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#925 -to=esc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#967 -to=nointerface
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1146 -to=bounded
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1243 -to=embedded
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1289 -to=colas
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1333 -to=diag
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1388 -to=noescape
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1494 -to=walkdef
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1513 -to=typecheck
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1532 -to=local
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1550 -to=dodata
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1569 -to=initorder
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1588 -to=used
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1606 -to=isddd
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1652 -to=implicit
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1670 -to=addrtaken
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1732 -to=assigned
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1786 -to=likely
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1834 -to=hasbreak
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/util.go:#95 -to=line
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#2349 -to=opt
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#2609 -to=setOpt
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#2158 -to=setVal
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#35954 -to=string
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#1992 -to=val
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#9785 -to=nodeEscState
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#9808 -to=curfn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#9828 -to=escflowsrc
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#9871 -to=escretval
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#9939 -to=escloopdepth
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#10086 -to=esclevel
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/esc.go:#10106 -to=walkgen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#13215 -to=nodeList
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#13262 -to=end
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#36502 -to=string
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gsubr.go:#3413 -to=nodindreg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#2055 -to=noreturn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5575 -to=oADDSTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5654 -to=oANDAND
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9486 -to=oANDNOT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5689 -to=oAPPEND
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5723 -to=oARRAYBYTESTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5790 -to=oARRAYBYTESTRTMP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7415 -to=oARRAYLIT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5868 -to=oARRAYRUNESTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6214 -to=oAS2
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6416 -to=oAS2DOTTYPE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6268 -to=oAS2FUNC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6363 -to=oAS2MAPR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6315 -to=oAS2RECV
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6468 -to=oASOP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6516 -to=oASWB
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10627 -to=oBLOCK
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10666 -to=oBREAK
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6571 -to=oCALL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6651 -to=oCALLFUNC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6775 -to=oCALLINTER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6707 -to=oCALLMETH
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6846 -to=oCALLPART
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6919 -to=oCAP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10686 -to=oCASE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12154 -to=oCFUNC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12222 -to=oCHECKNIL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6950 -to=oCLOSE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6983 -to=oCLOSURE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12086 -to=oCLOSUREVAR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7038 -to=oCMPIFACE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7117 -to=oCMPSTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10575 -to=oCOMPLEX
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7195 -to=oCOMPLIT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10861 -to=oCONTINUE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7596 -to=oCONVIFACE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7660 -to=oCONVNOP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7721 -to=oCOPY
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7760 -to=oDCL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7987 -to=oDCLCONST
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7904 -to=oDCLFIELD
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7865 -to=oDCLFUNC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8017 -to=oDCLTYPE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11708 -to=oDDD
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11785 -to=oDDDARG
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10884 -to=oDEFER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8045 -to=oDELETE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8265 -to=oDOTINTER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8193 -to=oDOTMETH
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8400 -to=oDOTTYPE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8484 -to=oDOTTYPE2
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11917 -to=oEFACE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12995 -to=oEND
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10967 -to=oFALL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11058 -to=oFOR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12950 -to=oGETG
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11105 -to=oGOTO
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11129 -to=oIF
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10549 -to=oIMAG
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8763 -to=oIND
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8837 -to=oINDEXMAP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11853 -to=oINLCALL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10503 -to=oIOTA
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11984 -to=oITAB
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8879 -to=oKEY
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11183 -to=oLABEL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9061 -to=oLEN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9086 -to=oMAKE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9168 -to=oMAKECHAN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9215 -to=oMAKEMAP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9261 -to=oMAKESLICE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7282 -to=oMAPLIT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9515 -to=oNEW
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5280 -to=oNONAME
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9540 -to=oNOT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9624 -to=oOROR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5381 -to=oPACK
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9653 -to=oPANIC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8966 -to=oPARAM
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9736 -to=oPAREN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9680 -to=oPRINT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9707 -to=oPRINTN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11203 -to=oPROC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7491 -to=oPTRLIT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11245 -to=oRANGE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10523 -to=oREAL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10215 -to=oRECOVER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10240 -to=oRECV
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12750 -to=oRETJMP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11292 -to=oRETURN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10262 -to=oRUNESTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11318 -to=oSELECT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10319 -to=oSELRECV
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10402 -to=oSELRECV2
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9758 -to=oSEND
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9787 -to=oSLICE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10007 -to=oSLICE3
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10120 -to=oSLICE3ARR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9882 -to=oSLICEARR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#9944 -to=oSLICESTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12035 -to=oSPTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5935 -to=oSTRARRAYBYTE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6002 -to=oSTRARRAYBYTETMP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#6080 -to=oSTRARRAYRUNE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#7347 -to=oSTRUCTLIT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11382 -to=oSWITCH
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11651 -to=oTARRAY
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11534 -to=oTCHAN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11631 -to=oTFUNC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11606 -to=oTINTER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11556 -to=oTMAP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11584 -to=oTSTRUCT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5358 -to=oTYPE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11460 -to=oTYPESW
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#12284 -to=oVARKILL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#10773 -to=oXCASE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#8333 -to=oXDOT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#11012 -to=oXFALL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#5219 -to=oXXX
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#1829 -to=optStats
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#1848 -to=ncvtreg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#1863 -to=nspill
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#1878 -to=nreload
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#1908 -to=nvar
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#1923 -to=naddr
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/order.go:#1648 -to=order
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6678 -to=pDISCARD
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6547 -to=pPARAM
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6577 -to=pPARAMOUT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#597 -to=pRIME1
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#17986 -to=panicindex
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3714 -to=param
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3730 -to=ntype
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3776 -to=outerexpr
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3841 -to=stackparam
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#3925 -to=field
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4002 -to=outer
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/syntax.go:#4054 -to=closure
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2345 -to=pkg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2359 -to=name
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2392 -to=path
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2452 -to=pathsym
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2467 -to=prefix
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2524 -to=imported
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2583 -to=exported
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2638 -to=direct
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2676 -to=safe
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2734 -to=syms
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#5572 -to=lookup
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#5856 -to=lookupBytes
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#31649 -to=ptrto
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6462 -to=pxxx
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#2968 -to=reg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/gsubr.go:#16941 -to=regdump
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#4129 -to=rgn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#17861 -to=sTORE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#34967 -to=sconv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#38318 -to=setmaxarg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7407 -to=sig
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#64119 -to=smagic
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#34153 -to=structfirst
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2767 -to=sym
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2781 -to=lexical
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2799 -to=flags
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2816 -to=link
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2832 -to=uniqgen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2850 -to=importdef
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2907 -to=linkname
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#2971 -to=pkg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3024 -to=def
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3088 -to=label
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3142 -to=block
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3199 -to=lastlineno
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3253 -to=origpkg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3305 -to=lsym
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3327 -to=fsym
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#34851 -to=string
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5678 -to=symAlgGen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5656 -to=symAsm
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5495 -to=symExport
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5557 -to=symExported
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5535 -to=symPackage
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5634 -to=symSiggen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5612 -to=symUniq
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#41208 -to=symlink
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6039 -to=tANY
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5972 -to=tARRAY
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6111 -to=tBLANK
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6003 -to=tCHAN
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6164 -to=tCHANARGS
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5905 -to=tCOMPLEX128
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5893 -to=tCOMPLEX64
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6031 -to=tFIELD
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6024 -to=tFORW
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5965 -to=tFUNC
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6153 -to=tFUNCARGS
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6097 -to=tIDEAL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6016 -to=tINTER
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6175 -to=tINTERMETH
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6010 -to=tMAP
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6105 -to=tNIL
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6045 -to=tSTRING
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5994 -to=tSTRUCT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#6054 -to=tUNSAFEPTR
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5980 -to=t_old_DARRAY
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/popt.go:#12257 -to=tempVar
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#5789 -to=txxx
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3396 -to=nointerface
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3414 -to=noalg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3433 -to=chan
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3452 -to=trecur
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3490 -to=printed
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3509 -to=embedded
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3552 -to=siggen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3571 -to=funarg
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3615 -to=copyany
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3634 -to=local
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3676 -to=deferwidth
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3695 -to=broke
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3741 -to=isddd
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3805 -to=haspointers
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3851 -to=nod
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3889 -to=orig
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3954 -to=lineno
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3977 -to=thistuple
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#3992 -to=outtuple
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4007 -to=intuple
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4022 -to=outnamed
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4040 -to=method
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4055 -to=xmethod
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4071 -to=sym
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4084 -to=vargen
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4130 -to=nname
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4174 -to=type
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4325 -to=down
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4384 -to=outer
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4415 -to=note
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4471 -to=bound
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4523 -to=bucket
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4581 -to=hmap
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4652 -to=hiter
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4716 -to=map
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4793 -to=maplineno
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4845 -to=embedlineno
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4955 -to=copyto
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#4974 -to=lastfn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#35257 -to=string
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/align.go:#7352 -to=typeList
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#16726 -to=typePairList
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7361 -to=name
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#7376 -to=etype
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/plive.go:#648 -to=uNVISITED
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#65274 -to=umagic
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/plive.go:#663 -to=vISITED
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1586 -to=val
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1936 -to=u
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/go.go:#1988 -to=ctype
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/reg.go:#2021 -to=var
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/fmt.go:#6308 -to=vconv
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/bv.go:#210 -to=wORDBITS
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/bv.go:#226 -to=wORDMASK
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/bv.go:#252 -to=wORDSHIFT
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/bv.go:#195 -to=wORDSIZE
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#3514 -to=warn
gorename -offset=/Users/craig/go/src/cmd/compile/internal/gc/subr.go:#2213 -to=yyerror