// generated by stringer -type boxsize; DO NOT EDIT

package main

import "fmt"

const _boxsizeName = "b1x1b1x2b1x3b1x4b2x1b2x2b2x3b2x4b3x1b3x2b3x3b3x4b4x1b4x2b4x3b4x4"

var _boxsizeIndex = [...]uint8{0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64}

func (i boxsize) String() string {
	if i < 0 || i+1 >= boxsize(len(_boxsizeIndex)) {
		return fmt.Sprintf("boxsize(%d)", i)
	}
	return _boxsizeName[_boxsizeIndex[i]:_boxsizeIndex[i+1]]
}
